CREATE TABLE movingday_contacts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contact_name TEXT NOT NULL,
  contact_phone TEXT,
  contact_email TEXT,
  contact_notes TEXT,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id INTEGER
    REFERENCES movingday_users(id) ON DELETE CASCADE NOT NULL
);