CREATE TABLE movingday_lists (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  list_name TEXT NOT NULL,
  list_items json,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id INTEGER
    REFERENCES movingday_users(id) ON DELETE CASCADE NOT NULL
);