CREATE TABLE movingday_boxes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  box_name TEXT NOT NULL,
  coming_from TEXT,
  going_to TEXT,
  getting_there TEXT,
  box_notes TEXT,
  inventory TEXT[],
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id INTEGER
    REFERENCES movingday_users(id) ON DELETE CASCADE NOT NULL
);
